# Calculate Eigenvector Centrality

In [26]:
import numpy as np
import networkx as nx

## graph of interest

In [4]:
graph = {
    0 : {3},
    1 : {7, 2, 8, 3, 4, 6, 5},
    2 : {1},
    3 : {1, 0, 4},
    4 : {5, 7, 1, 8, 3, 9, 10, 6},
    5 : {1, 4},
    6 : {1, 4},
    7 : {1, 4},
    8 : {4, 1},
    9 : {4},
    10: {4}
}

In [5]:
G = nx.Graph()

In [10]:
for node in graph:
    G.add_node(node)
    for neighbor in graph[node]:
        G.add_edge(node, neighbor)

In [12]:
print(nx.info(G))

Name: 
Type: Graph
Number of nodes: 11
Number of edges: 15
Average degree:   2.7273


## check what NetworkX thinks...

In [14]:
centrality = nx.eigenvector_centrality(G)

In [15]:
print(['%s %0.2f'%(node,centrality[node]) for node in centrality])

['0 0.07', '1 0.52', '2 0.13', '3 0.29', '4 0.55', '5 0.27', '6 0.27', '7 0.27', '8 0.27', '9 0.14', '10 0.14']


In [16]:
centrality

{0: 0.07285964283167869,
 1: 0.5171636983834933,
 2: 0.13093584707220737,
 3: 0.2877790124175975,
 4: 0.5466310265698511,
 5: 0.26933231425876697,
 6: 0.26933231425876697,
 7: 0.26933231425876697,
 8: 0.26933231425876697,
 9: 0.13839646718655957,
 10: 0.13839646718655957}

In [49]:
result1 = list(centrality.values())

In [50]:
result1

[0.07285964283167869,
 0.5171636983834933,
 0.13093584707220737,
 0.2877790124175975,
 0.5466310265698511,
 0.26933231425876697,
 0.26933231425876697,
 0.26933231425876697,
 0.26933231425876697,
 0.13839646718655957,
 0.13839646718655957]

In [51]:
sum(list(centrality.values()))

2.9094914186830145

## create adjacency matrix for the graph

In [37]:
n = len(G.nodes())

In [38]:
A = np.zeros([n,n], dtype=int)

In [39]:
A

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### set A<sub>ij</sub> = 1 where an edge exists between nodes

In [44]:
for i in range(n):
    for j in range(i+1,n):
        if G.has_edge(i, j):
            A[i][j] = 1
            A[j][i] = 1

In [45]:
A

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]])

## Power Iteration
(from: https://en.wikipedia.org/wiki/Power_iteration)

In [27]:
def power_iteration(A, num_simulations):
    # Ideally choose a random vector
    # To decrease the chance that our vector
    # Is orthogonal to the eigenvector
    b_k = np.random.rand(A.shape[0])

    for _ in range(num_simulations):
        # calculate the matrix-by-vector product Ab
        b_k1 = np.dot(A, b_k)

        # calculate the norm
        b_k1_norm = np.linalg.norm(b_k1)

        # re normalize the vector
        b_k = b_k1 / b_k1_norm

    return b_k

In [46]:
num_simulations = 10

In [48]:
result2 = power_iteration(A, num_simulations)

In [52]:
result2

array([ 0.07295677,  0.517467  ,  0.13084271,  0.28748759,  0.54710113,
        0.26907311,  0.26907311,  0.26907311,  0.26907311,  0.1382304 ,
        0.1382304 ])

In [53]:
sum(result2)

2.9086084282997913

## scale the results

$z_{i} = \frac{x_{i} * DesiredSum}{\sum_{i=1}^{n}x_{i}}$

In [65]:
DesiredSum = n

In [66]:
z = np.zeros(n)

In [67]:
x = result2

In [68]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [69]:
x

array([ 0.07295677,  0.517467  ,  0.13084271,  0.28748759,  0.54710113,
        0.26907311,  0.26907311,  0.26907311,  0.26907311,  0.1382304 ,
        0.1382304 ])

In [70]:
for i in range(n):
    z[i] = (x[i] * DesiredSum) / sum(x)

In [71]:
z

array([ 0.27591353,  1.95699668,  0.49483106,  1.08724275,  2.06906931,
        1.01760147,  1.01760147,  1.01760147,  1.01760147,  0.5227704 ,
        0.5227704 ])

In [72]:
sum(z)

11.0

In [73]:
z[7]

1.0176014656252592